# Generated by Django 4.2.7 on 2025-09-20 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image Message'), ('file', 'File Attachment'), ('system', 'System Message')], default='text', help_text='Type of message content', max_length=10, verbose_name='Message Type')),
                ('content', models.TextField(blank=True, help_text='Text content of the message', null=True, verbose_name='Message Content')),
                ('attachment_url', models.URLField(blank=True, help_text='URL to attached file or image', null=True, verbose_name='Attachment URL')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by recipient', verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was read', null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recipient', models.ForeignKey(help_text='User who received the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'created_at'], name='messages_sender__e179b4_idx'), models.Index(fields=['recipient', 'is_read'], name='messages_recipie_6234cf_idx')],
            },
        ),
    ]
